# -*- coding: utf-8 -*-
"""Coinflex.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1doTeUtt4RQUtN9ETMrkp0yOgJYHqRBEl
"""

API_KEY = "ArQ/f2IISIoHQx6aTVO3TMZB5z+cZuPTudwFf24dDhE="
SECRET = "sijyFgxg55zc9av2wlfOZTxgQbRKqFYnjoxmwx1SfR8="

# Authentication

import requests
import hmac
import base64
import hashlib
import datetime
from urllib.parse import urlencode

rest_url = 'https://v2stgapi.coinflex.com'
rest_path = 'v2stgapi.coinflex.com'

api_key = API_KEY
api_secret = SECRET

ts = datetime.datetime.utcnow().isoformat()
nonce = 123
method = "/v2/positions"

# Optional and can be omitted depending on the REST method being called 
# body = urlencode({'key1': 'value1', 'key2': 'value2'})

# if body:
    # path = method + '?' + body
#else:

path = method

msg_string = '{}\n {}\n {}\n {}\n {}\n'.format(ts, nonce, 'GET', rest_path, method)
sig = base64.b64encode(hmac.new(api_secret.encode('utf-8'), msg_string.encode('utf-8'), hashlib.sha256).digest()).decode('utf-8')

header = {'Content-Type': 'application/json', 'AccessKey': api_key,
          'Timestamp': ts, 'Signature': sig, 'Nonce': str(nonce)}

resp = requests.get(rest_url + path, headers=header)
print(resp.json())

msg_string

# Example POST

method = '/v3/AMM/create' 

# Required for POST 
body = urlencode({
    "direction": "BUY",
    "marketCode": "BCH-USD-SWAP-LIN",
    "counterQuantity": "250",
    "minPriceBound": "200",
    "maxPriceBound": "800"
})

if body:
    path = method + '?' + body
else:
    path = method

msg_string = '{}\n{}\n{}\n{}\n{}\n{}'.format(ts, nonce, 'POST', rest_path, method, body)
sig = base64.b64encode(hmac.new(api_secret.encode('utf-8'), msg_string.encode('utf-8'), hashlib.sha256).digest()).decode('utf-8')

header = {'Content-Type': 'application/json', 'AccessKey': api_key,
          'Timestamp': ts, 'Signature': sig, 'Nonce': str(nonce)}

resp = requests.post(rest_url + path, headers=header)
print(resp.json())

msg_string